# Generated by Django 4.0.4 on 2022-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner_bid',
            field=models.FloatField(default=0),
        ),
    ]
