# Generated by Django 4.0.5 on 2022-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslisting',
            name='image_url',
            field=models.URLField(max_length=6000),
        ),
    ]
