# Generated by Django 4.0.5 on 2022-07-17 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionslisting_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslisting',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
