# Generated by Django 4.0.4 on 2022-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_winner_winner_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.AddField(
            model_name='winner',
            name='winner_user',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
