# Generated by Django 4.1 on 2022-08-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_category_listing_auctionslisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=6000, null=True),
        ),
    ]
