# Generated by Django 4.0.5 on 2022-07-17 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionslisting_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionslisting',
            name='user_id',
        ),
        migrations.AddField(
            model_name='auctionslisting',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
