# Generated by Django 4.0.5 on 2022-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='auction',
        ),
        migrations.AddField(
            model_name='category',
            name='auction',
            field=models.ManyToManyField(default=None, related_name='categories', to='auctions.auctionslisting'),
        ),
    ]
